version: "3"
services:
  gc_db:
    image: postgres:alpine
    container_name: "gc_db"
    env_file:
      - .env
      - config/private/prod/secrets.env 
      
  gc_server:
    build:
      context: ./
      dockerfile: ./config/docker/django/prod/Dockerfile
    image: gc_server
    container_name: "gc_server"
    volumes:
      - ./data:/app_data
    env_file:
      - .env
      - config/private/prod/secrets.env
      - config/private/prod/super-secrets.env
    depends_on:
      - gc_db

  gc_web:
    build:
      context: ./
      dockerfile: ./config/docker/web/prod/Dockerfile
    image: "gc_web"
    container_name: gc_web
    ports:
      - "80:80"
    volumes:
      - ./data:/app_data
    depends_on:
      - gc_server

